<?php

use Illuminate\Database\Seeder;
use App\Models\JobPosition;

class JobPositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $jobPositions = [
            [
                'id' => 1,
                'JobPositionName' => 'Area Manager',
                'TypeofJob' => 'ควบคุมงาน บริหารงาน และใหคําปรึกษา',
                'craft_id' => 2,
                'created_at' => '2020-01-21 06:05:00',
                'updated_at' => '2021-02-24 05:42:00',
            ],
            [
                'id' => 2,
                'JobPositionName' => 'Supervisor',
                'TypeofJob' => 'ควบคุมงาน และใหคําปรึกษา',
                'craft_id' => 2,
                'created_at' => '2020-01-21 06:06:00',
                'updated_at' => '2020-01-21 06:06:00',
            ],
            [
                'id' => 3,
                'JobPositionName' => 'Foreman',
                'TypeofJob' => 'ควบคุมงานในการถอด - ประกอบ',
                'craft_id' => 3,
                'created_at' => '2020-01-21 06:06:00',
                'updated_at' => '2020-01-21 06:06:00',
            ],
            [
                'id' => 4,
                'JobPositionName' => 'Skills',
                'TypeofJob' => 'ปฏิบัติงานในการถอด - ประกอบ',
                'craft_id' => 4,
                'created_at' => '2020-01-21 06:06:00',
                'updated_at' => '2020-01-21 06:06:00',
            ],
            [
                'id' => 5,
                'JobPositionName' => 'IMMM/Inspector',
                'TypeofJob' => 'ควบคุมผูรับจางในการปฏิบัติงาน',
                'craft_id' => 4,
                'created_at' => '2020-01-21 06:07:00',
                'updated_at' => '2020-01-21 06:07:00',
            ],
            [
                'id' => 6,
                'JobPositionName' => 'Site Engineer',
                'TypeofJob' => 'ออกแบบ และใหคําปรึกษาในงานบํารุงรักษา',
                'craft_id' => 2,
                'created_at' => '2020-01-21 06:07:00',
                'updated_at' => '2020-01-21 06:07:00',
            ],
            [
                'id' => 7,
                'JobPositionName' => 'Store Keeper',
                'TypeofJob' => 'ควบคุมการจําหนายเครื่องมืออุปกรณ',
                'craft_id' => 4,
                'created_at' => '2020-01-21 06:07:00',
                'updated_at' => '2020-01-21 06:07:00',
            ],
            [
                'id' => 8,
                'JobPositionName' => 'Technical Report',
                'TypeofJob' => 'จัดการงานธุรการในภาคสนาม',
                'craft_id' => 4,
                'created_at' => '2020-01-21 06:07:00',
                'updated_at' => '2020-01-21 06:07:00',
            ],
            [
                'id' => 9,
                'JobPositionName' => 'Stationary Crane Operator',
                'TypeofJob' => 'ผูบังคับปนจั่นอยูกับที่',
                'craft_id' => 4,
                'created_at' => '2020-01-21 06:08:00',
                'updated_at' => '2020-01-21 06:08:00',
            ],
            [
                'id' => 10,
                'JobPositionName' => 'Planner',
                'TypeofJob' => 'วางแผนงาน',
                'craft_id' => 2,
                'created_at' => '2021-11-01 01:51:00',
                'updated_at' => '2021-11-01 01:51:00',
            ],
            [
                'id' => 12,
                'JobPositionName' => 'Head Engineering',
                'TypeofJob' => 'บริหารงานวิศวกรรม และแผนงานบํารุงรักษา',
                'craft_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 13,
                'JobPositionName' => 'Head Operation',
                'TypeofJob' => 'บริหารงานบํารุงรักษาโรงไฟฟา และคลังเครื่องมือ',
                'craft_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 14,
                'JobPositionName' => 'Head Diving',
                'TypeofJob' => 'บริหารงานบํารุงรักษาใตนํ้า',
                'craft_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 16,
                'JobPositionName' => 'Confined Space Permitter',
                'TypeofJob' => 'ผูอนุญาตงานในที่อับอากาศ',
                'craft_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 17,
                'JobPositionName' => 'Confined Space Supervisor',
                'TypeofJob' => 'ผูควบคุมงานในที่อับอากาศ',
                'craft_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 18,
                'JobPositionName' => 'Confined Space Helper',
                'TypeofJob' => 'ผูชวยเหลือในที่อับอากาศ',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 19,
                'JobPositionName' => 'Confined Space Worker',
                'TypeofJob' => 'ผูปฏิบัติงานที่อับอากาศ',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 20,
                'JobPositionName' => 'Diving Foreman',
                'TypeofJob' => 'หัวหนานักประดานํ้า',
                'craft_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 21,
                'JobPositionName' => 'Diver',
                'TypeofJob' => 'พี่เลี้ยงนักประดานํ้า นักประดานํ้า นักประดานํ้าพรอมดํา ผูควบคุมจายอากาศและติดตอสื่อสาร',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 22,
                'JobPositionName' => 'Diving Nurse',
                'TypeofJob' => 'พยาบาลเวชศาสตรใตนํ้า/เจาหนาที่เวชศาสตรใตนํ้า',
                'craft_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 23,
                'JobPositionName' => 'Welder',
                'TypeofJob' => 'ชางเชื่อม/ตัด ดวยแกส หรือไฟฟา',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 24,
                'JobPositionName' => 'Fire Watcher',
                'TypeofJob' => 'ผูเฝาระวังอัคคีภัย',
                'craft_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 25,
                'JobPositionName' => 'Scaffold Installer',
                'TypeofJob' => 'ผูติดตั้งและรื้อถอนนั่งราน',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 26,
                'JobPositionName' => 'Scaffold Inspector',
                'TypeofJob' => 'ผูตรวจสอบนั่งราน',
                'craft_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 27,
                'JobPositionName' => 'Stationary Crane Signaler',
                'TypeofJob' => 'ผูใหสัญญาณปนจั่นอยูกับที่',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 28,
                'JobPositionName' => 'Stationary Crane Rigger',
                'TypeofJob' => 'ผูยึดเกาะปนจั่นอยูกับที่',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 29,
                'JobPositionName' => 'Stationary Crane Supervisor',
                'TypeofJob' => 'ผูควบคุมการใชปนจั่นอยูกับที่',
                'craft_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 30,
                'JobPositionName' => 'Mobile Crane Signaler',
                'TypeofJob' => 'ผูใหสัญญาณปนจั่นเคลื่อนที่',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 31,
                'JobPositionName' => 'Mobile Crane Rigger',
                'TypeofJob' => 'ผูยึดเกาะปนจั่นเคลื่อนที่',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 32,
                'JobPositionName' => 'Mobile Crane Supervisor',
                'TypeofJob' => 'ผูควบคุมการใชปนจั่นเคลื่อนที่',
                'craft_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 33,
                'JobPositionName' => 'Dilling Supervisor',
                'TypeofJob' => 'ผูควบคุมงานขุดเจาะ',
                'craft_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 34,
                'JobPositionName' => 'Constructoin Engineer',
                'TypeofJob' => 'วิศวกรควบคุมงานกอสราง',
                'craft_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 35,
                'JobPositionName' => 'Ray Safety Officer',
                'TypeofJob' => 'จป. รังสี',
                'craft_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 36,
                'JobPositionName' => 'Ray Worker',
                'TypeofJob' => 'ผูปฏิบัติงานทางรังสี',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 37,
                'JobPositionName' => 'Chemical Worker',
                'TypeofJob' => 'ผูปฏิบัติงานเกี่ยวกับสารเคมี',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 38,
                'JobPositionName' => 'Electrical Worker',
                'TypeofJob' => 'ผูปฏิบัติงานที่ทํางานเกี่ยวกับไฟฟา',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 39,
                'JobPositionName' => 'Flok Lift Driver',
                'TypeofJob' => 'ผูขับรถโฟลคลิฟต',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 40,
                'JobPositionName' => 'Boom Lift Driver',
                'TypeofJob' => 'ผูขับรถกระเชา',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 41,
                'JobPositionName' => 'Backhol Driver',
                'TypeofJob' => 'ผูขับรถขุด',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 42,
                'JobPositionName' => 'Work at Hight Worker',
                'TypeofJob' => 'ผูปฏิบัติงานบนที่สูง',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 43,
                'JobPositionName' => 'Moblie Crane Operator',
                'TypeofJob' => 'ผูบังคับปนจั่นเคลื่อนที่',
                'craft_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 44,
                'JobPositionName' => 'Safety Officer Supervisory level',
                'TypeofJob' => 'จป. หัวหนางาน',
                'craft_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
        ];

        foreach ($jobPositions as $position) {
            JobPosition::create($position);
        }
    }
}
